const raw=`Adana|37.00|35.32;Adıyaman|37.76|38.28;Afyonkarahisar|38.76|30.54;Ağrı|39.72|43.05;Amasya|40.65|35.83;Ankara|39.93|32.86;Antalya|36.89|30.70;Artvin|41.18|41.82;Aydın|37.85|27.85;Balıkesir|39.65|27.88;Bilecik|40.14|29.98;Bingöl|38.89|40.50;Bitlis|38.40|42.11;Bolu|40.74|31.61;Burdur|37.72|30.29;Bursa|40.19|29.06;Çanakkale|40.15|26.41;Çankırı|40.60|33.62;Çorum|40.55|34.95;Denizli|37.78|29.09;Diyarbakır|37.91|40.24;Edirne|41.68|26.56;Elazığ|38.68|39.22;Erzincan|39.75|39.49;Erzurum|39.90|41.27;Eskişehir|39.77|30.52;Gaziantep|37.06|37.38;Giresun|40.92|38.39;Gümüşhane|40.46|39.48;Hakkari|37.58|43.74;Hatay|36.20|36.16;Isparta|37.76|30.55;Mersin|36.80|34.63;İstanbul|41.008|28.978;İzmir|38.42|27.14;Kars|40.60|43.10;Kastamonu|41.38|33.78;Kayseri|38.72|35.49;Kırklareli|41.73|27.22;Kırşehir|39.15|34.16;Kocaeli|40.77|29.94;Konya|37.87|32.49;Kütahya|39.42|29.98;Malatya|38.35|38.31;Manisa|38.61|27.43;Kahramanmaraş|37.58|36.93;Mardin|37.31|40.74;Muğla|37.22|28.36;Muş|38.75|41.51;Nevşehir|38.62|34.71;Niğde|37.97|34.68;Ordu|40.98|37.88;Rize|41.02|40.52;Sakarya|40.77|30.40;Samsun|41.29|36.33;Siirt|37.93|41.94;Sinop|42.03|35.15;Sivas|39.75|37.02;Tekirdağ|40.98|27.51;Tokat|40.32|36.55;Trabzon|41.00|39.73;Tunceli|39.11|39.55;Şanlıurfa|37.17|38.79;Uşak|38.68|29.41;Van|38.50|43.38;Yozgat|39.82|34.81;Zonguldak|41.45|31.79;Aksaray|38.37|34.03;Bayburt|40.26|40.23;Karaman|37.18|33.22;Kırıkkale|39.85|33.51;Batman|37.88|41.13;Şırnak|37.52|42.46;Bartın|41.63|32.34;Ardahan|41.11|42.70;Iğdır|39.92|44.05;Yalova|40.65|29.27;Karabük|41.20|32.62;Kilis|36.72|37.12;Osmaniye|37.07|36.25;Düzce|40.84|31.16`;
const cities=Object.fromEntries(raw.split(';').map(s=>{const[n,lat,lon]=s.split('|');return[n,[+lon,+lat]]}));const $=id=>document.getElementById(id);const fmt=(n,d=0)=>n.toLocaleString('tr-TR',{maximumFractionDigits:d});const money=n=>fmt(n,0)+' ₺';let map,line,markers=[],routes=[],active=0,km=null,seconds=null,request=0,controller;
for(const id of ['from','to'])for(const n of Object.keys(cities).sort((a,b)=>a.localeCompare(b,'tr'))){const o=document.createElement('option');o.value=o.textContent=n;$(id).append(o)}$('from').value='İstanbul';$('to').value='Ankara';
if(window.L){map=L.map('map',{zoomControl:false,minZoom:5,maxBounds:[[34,24],[44,47]]}).setView([39,34],6);L.control.zoom({position:'topright'}).addTo(map);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap',maxZoom:18}).addTo(map)}else $('map').textContent='Harita yüklenemedi. Rota ve maliyet hesabını aşağıdan kullanabilirsin.';
let country;
async function loadCountry(signal){if(country)return country;const response=await fetch('/turkiye.json',{signal});if(!response.ok)throw new Error('boundary');country=await response.json();return country;}
function inRing(p,ring){let inside=false;for(let i=0,j=ring.length-1;i<ring.length;j=i++){const a=ring[i],b=ring[j];if((a[1]>p[1])!==(b[1]>p[1])&&p[0]<(b[0]-a[0])*(p[1]-a[1])/(b[1]-a[1])+a[0])inside=!inside}return inside}
// The country outline is generalized: reclaimed land and coastal roads can lie
// just outside it. Use a 1 km cartographic tolerance, not an exact land mask.
function nearRing(p,ring){const xScale=111320*Math.cos(p[1]*Math.PI/180),yScale=111320;for(let i=0,j=ring.length-1;i<ring.length;j=i++){const ax=(ring[j][0]-p[0])*xScale,ay=(ring[j][1]-p[1])*yScale,bx=(ring[i][0]-p[0])*xScale,by=(ring[i][1]-p[1])*yScale;const dx=bx-ax,dy=by-ay,len=dx*dx+dy*dy;const t=len?Math.max(0,Math.min(1,-(ax*dx+ay*dy)/len)):0;if((ax+t*dx)**2+(ay+t*dy)**2<=1000**2)return true}return false}
function inTurkey(p,g){const polygons=g.type==='Polygon'?[g.coordinates]:g.coordinates;return polygons.some(poly=>inRing(p,poly[0])&&!poly.slice(1).some(h=>inRing(p,h)))||polygons.some(poly=>nearRing(p,poly[0]))}
function eligibleRoute(r,boundary){return !r.legs.some(l=>l.steps.some(s=>s.mode==='ferry'||!inTurkey(s.maneuver.location,boundary)))}
function clearMap(){if(line&&map)map.removeLayer(line);line=null;markers.forEach(m=>map.removeLayer(m));markers=[]}
function recalc(){const c=+$('consumption').value,p=+$('price').value,t=$('toll').value,trip=+document.querySelector('[name=trip]:checked').value;const valid=c>0&&c<=100&&p>0&&(t===''||+t>=0);$('rate').textContent=fmt(c,1)+' L / 100 km tüketimle';$('fuelcaption').textContent=$('fueltype').value+' · '+fmt(p,2)+' ₺/L';if(km===null||!valid){for(const id of ['distance','liters','fuelcost','total','bfuel','perkm'])$(id).textContent='—';$('totalnote').textContent=valid?'Önce rotanı hesapla.':'Tüketim, fiyat ve ücret alanlarını kontrol et.';return}const distance=km*trip,liters=distance*c/100,cost=liters*p,total=cost+(+t)*trip;$('distance').innerHTML=fmt(distance)+' <small>km</small>';$('liters').innerHTML=fmt(liters,1)+' <small>litre</small>';$('fuelcost').textContent=$('bfuel').textContent=money(cost);$('btoll').textContent=t===''?'Girilmedi':money(+t*trip);$('total').textContent=money(total);$('totalnote').textContent=t===''?'Yalnızca yakıt • Yol ücretini ekleyerek tamamla':(trip===2?'Gidiş-dönüş':'Tek yön')+' · Yakıt + yol ve köprü ücretleri';$('perkm').textContent=fmt(total/distance,2)+' ₺/km';$('duration').textContent=seconds===null?'Manuel mesafe':Math.floor(seconds*trip/3600)+' sa '+Math.round((seconds*trip%3600)/60)+' dk · molasız';}
function choose(i){active=i;clearMap();const r=routes[i];km=r.distance/1000;seconds=r.duration;if(map){line=L.geoJSON(r.geometry,{style:{color:'#286644',weight:5,opacity:.95}}).addTo(map);map.fitBounds(line.getBounds(),{padding:[40,65]});for(const [idx,name]of [$('from').value,$('to').value].entries()){const [lon,lat]=cities[name];markers.push(L.marker([lat,lon],{icon:L.divIcon({className:'',html:`<div style="background:${idx?'#194f43':'white'};color:${idx?'white':'#194f43'};border:3px solid #194f43;border-radius:50%;width:29px;height:29px;text-align:center;font-weight:bold;line-height:23px">${idx?'B':'A'}</div>`,iconSize:[29,29]})}).addTo(map).bindTooltip(name))}}[...$('alternatives').children].forEach((b,j)=>b.classList.toggle('active',i===j));recalc()}
function invalidate(){request++;controller?.abort();km=null;seconds=null;routes=[];clearMap();$('alternatives').replaceChildren();$('route-label').textContent='Yeni rota seçildi';$('gmaps').removeAttribute('href');$('duration').textContent='Rotayı yeniden hesapla';$('status').textContent='Yeni güzergâh için Rotayı hesapla’ya bas.';$('calculate').disabled=false;recalc()}
async function route(){
 const my=++request;controller?.abort();const current=new AbortController();controller=current;
 km=null;seconds=null;routes=[];clearMap();$('alternatives').replaceChildren();$('duration').textContent='Rota hesaplanıyor';recalc();
 if($('from').value===$('to').value){$('status').textContent='Başlangıç ve varış için farklı iller seç.';$('calculate').disabled=false;return}
 $('calculate').disabled=true;$('status').textContent='Yol ağı üzerinden rota bulunuyor…';
 const a=cities[$('from').value],b=cities[$('to').value];$('route-label').textContent=$('from').value+' → '+$('to').value;
 $('gmaps').href='https://www.google.com/maps/dir/?api=1&origin='+a[1]+','+a[0]+'&destination='+b[1]+','+b[0]+'&travelmode=driving';
 const timer=setTimeout(()=>current.abort(),30000);
 try{
  const boundary=await loadCountry(current.signal);
  const res=await fetch('https://router.project-osrm.org/route/v1/driving/'+a.join(',')+';'+b.join(',')+'?overview=full&geometries=geojson&alternatives=true&steps=true',{signal:current.signal});
  if(!res.ok)throw new Error('service');const data=await res.json();if(my!==request)return;
  if(data.code!=='Ok'||!data.routes?.length)throw new Error('no-route');
  routes=data.routes.filter(r=>eligibleRoute(r,boundary)).slice(0,3);
  if(!routes.length)throw new Error('outside');
  routes.forEach((r,i)=>{const btn=document.createElement('button');btn.type='button';btn.textContent=(i===0?'Önerilen rota':'Alternatif '+i)+' · '+fmt(r.distance/1000)+' km';btn.onclick=()=>choose(i);$('alternatives').append(btn)});
  choose(0);$('status').textContent='Rota hazır. Gişe ve köprü ücretini tarifeden ekle.';
 }catch(e){
  if(my!==request)return;
  const messages={'boundary':'Türkiye harita verisi yüklenemedi. Sayfayı yenileyip tekrar dene.','no-route':'Bu iki il arasında rota bulunamadı. Farklı bir güzergâh seçebilirsin.','outside':'Bulunan rotalar feribot veya Türkiye dışı geçiş içeriyor. Google Maps’ten bir kara yolu rotası seçip mesafesini girebilirsin.'};
  $('status').textContent=e.name==='AbortError'?'Rota hizmeti zamanında yanıt vermedi. Tekrar dene veya manuel mesafe gir.':messages[e.message]||'Rota hizmetine bağlanılamadı. İnternet bağlantını kontrol edip tekrar dene veya manuel mesafe gir.';
  $('duration').textContent='Rota alınamadı';
 }finally{clearTimeout(timer);if(my===request)$('calculate').disabled=false}
}
$('planner').onsubmit=e=>{e.preventDefault();route()};$('swap').onclick=()=>{const v=$('from').value;$('from').value=$('to').value;$('to').value=v;invalidate();route()};for(const id of ['from','to'])$(id).onchange=invalidate;for(const id of ['consumption','price','toll','fueltype'])$(id).addEventListener('input',recalc);document.querySelectorAll('[name=trip]').forEach(el=>el.onchange=recalc);$('usemanual').onclick=()=>{const value=+$('manual').value;if(!(value>0)){ $('manual').reportValidity();return }invalidate();km=value;seconds=null;$('status').textContent='Girdiğin manuel mesafe kullanılıyor.';$('route-label').textContent='Manuel mesafe · Harita rotası yok';recalc()};route();
// Elektrikli araç modu
const fuelTabs=document.createElement('div');fuelTabs.className='fuel-tabs';fuelTabs.innerHTML='<button type="button" class="active">Benzin / Motorin / LPG</button><button type="button">Elektrikli</button>';$('fueltype').parentElement.before(fuelTabs);
const electricBox=document.createElement('div');electricBox.className='electric-box';electricBox.hidden=true;electricBox.innerHTML='<div class="inputpair"><div><label for="electricConsumption">Tüketim</label><div class="unitinput"><input id="electricConsumption" type="number" min="1" step="0.1" value="18"><span>kWh/100 km</span></div></div><div><label for="electricPrice">Elektrik fiyatı</label><div class="unitinput"><input id="electricPrice" type="number" min="0.01" step="0.01" value="4"><span>₺/kWh</span></div></div></div>';$('fueltype').parentElement.after(electricBox);let electric=false;
fuelTabs.querySelectorAll('button').forEach((b,i)=>b.onclick=()=>{electric=i===1;fuelTabs.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));$('fueltype').parentElement.hidden=electric;electricBox.hidden=!electric;recalc()});
const oldRecalc=recalc;recalc=()=>{if(!electric){oldRecalc();return}const c=+$('electricConsumption').value,p=+$('electricPrice').value,t=$('toll').value,trip=+document.querySelector('[name=trip]:checked').value;const valid=c>0&&p>0&&(t===''||+t>=0);$('rate').textContent=fmt(c,1)+' kWh / 100 km tüketimle';$('fuelcaption').textContent='Elektrik · '+fmt(p,2)+' ₺/kWh';if(km===null||!valid){for(const id of ['distance','liters','fuelcost','total','bfuel','perkm'])$(id).textContent='—';return}const distance=km*trip,energy=distance*c/100,cost=energy*p,total=cost+(+t)*trip;$('distance').innerHTML=fmt(distance)+' <small>km</small>';$('liters').innerHTML=fmt(energy,1)+' <small>kWh</small>';$('fuelcost').textContent=$('bfuel').textContent=money(cost);$('btoll').textContent=t===''?'Girilmedi':money(+t*trip);$('total').textContent=money(total);$('perkm').textContent=fmt(total/distance,2)+' ₺/km';$('totalnote').textContent='Elektrik + yol ve köprü ücretleri'};
document.querySelectorAll('#electricConsumption,#electricPrice').forEach(x=>x.addEventListener('input',recalc));recalc();
// Sekmeler yalnızca araç bilgileri alanını değiştirir; rota/harita sabit kalır.
fuelTabs.remove();electricBox.remove();
const fuelLabel=document.querySelector('label[for="fueltype"]');
fuelLabel.parentNode.insertBefore(fuelTabs,fuelLabel);
const fuelPair=document.querySelector('#consumption').closest('.inputpair');
fuelPair.after(electricBox);
const districtWrap=document.createElement('div');districtWrap.className='districts';districtWrap.innerHTML='<div><label for="fromDistrict">Başlangıç ilçesi (isteğe bağlı)</label><input id="fromDistrict" placeholder="Örn. Kadıköy"></div><div><label for="toDistrict">Varış ilçesi (isteğe bağlı)</label><input id="toDistrict" placeholder="Örn. Merkez"></div>';
document.querySelector('#to').after(districtWrap);
async function geocode(place,fallback){if(!place.trim())return fallback;try{const r=await fetch('https://nominatim.openstreetmap.org/search?format=jsonv2&countrycodes=tr&limit=1&q='+encodeURIComponent(place+', Türkiye'));const d=await r.json();return d[0]?[+d[0].lon,+d[0].lat]:fallback}catch{return fallback}}
const originalRoute=route;route=async function(){const fromName=$('from').value,toName=$('to').value;const a0=cities[fromName],b0=cities[toName];const [a,b]=await Promise.all([geocode($('fromDistrict').value?$('fromDistrict').value+', '+fromName:a0,a0),geocode($('toDistrict').value?$('toDistrict').value+', '+toName:b0,b0)]);const oldA=cities[fromName],oldB=cities[toName];cities[fromName]=a;cities[toName]=b;try{return await originalRoute()}finally{cities[fromName]=oldA;cities[toName]=oldB}};
// İl ve ilçeyi tek arama kutusunda kullan
districtWrap.remove();
for(const id of ['from','to']){const old=$(id),input=document.createElement('input');input.id=id;input.setAttribute('list',id+'-places');input.placeholder='İl veya ilçe yazın';input.value=old.value;const list=document.createElement('datalist');list.id=id+'-places';Object.keys(cities).sort((a,b)=>a.localeCompare(b,'tr')).forEach(n=>{const o=document.createElement('option');o.value=n;list.append(o)});old.replaceWith(input);input.after(list);input.addEventListener('change',invalidate)}
route=async function(){const fromName=$('from').value.trim(),toName=$('to').value.trim();const a0=cities[fromName]||[34,39],b0=cities[toName]||[35,39];const [a,b]=await Promise.all([geocode(fromName,a0),geocode(toName,b0)]);const oldA=cities[fromName],oldB=cities[toName];cities[fromName]=a;cities[toName]=b;try{return await originalRoute()}finally{if(oldA)cities[fromName]=oldA;else delete cities[fromName];if(oldB)cities[toName]=oldB;else delete cities[toName]}};
let allPlaces=[];async function addDistrictOptions(){try{const r=await fetch('https://turkiyeapi.dev/api/v1/districts');if(!r.ok)return;const j=await r.json();const rows=j.data||[];rows.forEach(x=>{const district=x.name||x.district,province=x.province?.name||x.provinceName||x.city?.name;if(district&&province)allPlaces.push(district+' ('+province+')')});for(const id of ['from','to']){const list=$(id+'-places');allPlaces.forEach(v=>{const o=document.createElement('option');o.value=v;list.append(o)})}}catch(e){}}
addDistrictOptions();
async function inspectTolls(){if(!map||!line)return;try{const b=line.getBounds(),q=`[out:json][timeout:20];(way["toll"="yes"](${b.getSouth()},${b.getWest()},${b.getNorth()},${b.getEast()});way["bridge"="yes"](${b.getSouth()},${b.getWest()},${b.getNorth()},${b.getEast()}););out tags center;`;const r=await fetch('https://overpass-api.de/api/interpreter?data='+encodeURIComponent(q));if(!r.ok)return;const names=[...new Set((await r.json()).elements.map(e=>e.tags?.name).filter(Boolean))];if(names.length)$('status').textContent='Rota üzerindeki geçişler: '+names.slice(0,5).join(', ')}catch(e){}}
const chooseWithTolls=choose;choose=(i)=>{chooseWithTolls(i);setTimeout(inspectTolls,150)};
// Yazarken ilçe önerileri göster
const districtNames=['Ereğli (Konya)','Ereğli (Zonguldak)','Erbaa (Tokat)','Erciş (Van)','Erdemli (Mersin)','Ergani (Diyarbakır)','Eruh (Siirt)','Erzincan (Merkez)','Erzurum (Yakutiye)'];
const fallbackPlaces=['Aydın (İl)','Ayvalık (Balıkesir)','Ayvacık (Çanakkale)','Ayancık (Sinop)','Aybastı (Ordu)','Ayrancı (Karaman)','Akören (Konya)','Akşehir (Konya)'];
for(const id of ['from','to']){const inp=$(id),box=document.createElement('div');box.className='autocomplete';inp.parentElement.style.position='relative';inp.parentElement.append(box);let timer;inp.addEventListener('input',()=>{clearTimeout(timer);const q=inp.value.trim().toLocaleLowerCase('tr');box.replaceChildren();if(q.length<2)return;const local=[...new Set([...fallbackPlaces,...Object.keys(cities),...allPlaces])].filter(v=>v.toLocaleLowerCase('tr').startsWith(q));local.slice(0,12).forEach(label=>{const b=document.createElement('button');b.type='button';b.textContent=label;b.onclick=()=>{inp.value=label;box.replaceChildren();invalidate()};box.append(b)});timer=setTimeout(async()=>{try{const r=await fetch('https://nominatim.openstreetmap.org/search?format=jsonv2&countrycodes=tr&addressdetails=1&limit=10&q='+encodeURIComponent(q+', Türkiye'));(await r.json()).forEach(v=>{const a=v.address||{},name=a.town||a.city||a.municipality||a.county||v.display_name.split(',')[0],province=a.province||a.state||'',label=province?name+' ('+province+')':v.display_name;if(![...box.children].some(x=>x.textContent===label)){const b=document.createElement('button');b.type='button';b.textContent=label;b.onclick=()=>{inp.value=label;box.replaceChildren();invalidate()};box.append(b)}})}catch(e){}},250)});document.addEventListener('click',e=>{if(e.target!==inp&&!box.contains(e.target))box.replaceChildren()})}
